#ifndef CHAINPARAMSSEEDS_H
#define CHAINPARAMSSEEDS_H
// List of fixed seed nodes for the bitcoin network
// AUTOGENERATED by contrib/devtools/generate-seeds.py

// Each line contains a 16-byte IPv6 address and a port.
// IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
static const unsigned int pnSeed[] =
{
    0x0CBA202D,
    0x099C202D,
    0xD7B0202D,
    0x9A303F2D,
    0xC06D3F2D,
    0x89043F2D,
    0xBA92202D,
    0xA3E4202D,
    0xFBB83D6C,
    0x747F3F2D,
};


static const unsigned int pnTestnetSeed[] = {

};
#endif
